export const key = 'scheduleNScripts'

const FOLLOWUPS = {
  GET: `${key}/FOLLOWUPS/GET`,
  ERROR: `${key}/FOLLOWUPS/ERROR`,
  SUCCESS: `${key}/FOLLOWUPS/SUCCESS`,
  PERMISSION: `${key}/FOLLOWUPS/PERMISSION`,
  SET: `${key}/FOLLOWUPS/SET`,
  INNER_PERMISSIONS: `${key}/FOLLOWUPS/INNER_PERMISSIONS`,
  SET_INNER_PERMISSIONS: `${key}/FOLLOWUPS/SET_INNER_PERMISSIONS`,
  GET_FEATURE_PERMISSIONS: `${key}/FOLLOWUPS/GET_FEATURE_PERMISSIONS`
}

const TOUCHPOINT = {
  OPEN: `${key}/TOUCHPOINT/OPEN`,
  EDIT: `${key}/TOUCHPOINT/EDIT`,
  EDIT_TOUCHPOINT: `${key}/TOUCHPOINT/EDIT_TOUCHPOINT`,
  EDIT_SUCCESS: `${key}/TOUCHPOINT/EDIT_SUCCESS`,
  EDIT_ERROR: `${key}/TOUCHPOINT/EDIT_ERROR`,
  NEW: `${key}/TOUCHPOINT/NEW`,
  NEW_SUCCESS: `${key}/TOUCHPOINT/NEW_SUCCESS`,
  NEW_ERROR: `${key}/TOUCHPOINT/NEW_ERROR`,
  DELETE: `${key}/TOUCHPOINT/DELETE`,
  DELETE_SUCCESS: `${key}/TOUCHPOINT/DELETE_SUCCESS`,
  DELETE_ERROR: `${key}/TOUCHPOINT/DELETE_ERROR`,
  CLOSE: `${key}/TOUCHPOINT/CLOSE`
}

const SCRIPTS = {
  GET: 'scheduleNScripts/SCRIPTS/GET',
  SAVE: 'scheduleNScripts/SCRIPTS/SAVE',
  EDIT: 'scheduleNScripts/SCRIPTS/EDIT'
}

const SEGMENTS = {
  CLOSE: `${key}/SEGMENTS/CLOSE`,
  GET: `${key}/SEGMENTS/GET`,
  SET: `${key}/SEGMENTS/SET`,
  GET_ATTRIBUTES: `${key}/SEGMENTS/GET_ATTRIBUTES`,
  SET_ATTRIBUTES: `${key}/SEGMENTS/SET_ATTRIBUTES`,
  SET_DATA: `${key}/SEGMENTS/SET_DATA`,
  SAVE: `${key}/SEGMENTS/SAVE`,
  DELETE: `${key}/SEGMENTS/DELETE`,
  GET_LOCATIONS: `${key}/SEGMENTS/GET_LOCATIONS`,
  SET_LOCATIONS: `${key}/SEGMENTS/SET_LOCATIONS`,
  GET_LIST: `${key}/SEGMENTS/GET_LIST`,
  SET_LIST: `${key}/SEGMENTS/SET_LIST`,
  GET_COPY_PROCESS: `${key}/SEGMENTS/GET_COPY_PROCESS`,
  SET_COPY_PROCESS: `${key}/SEGMENTS/SET_COPY_PROCESS`,
  SET_ALERT: `${key}/SEGMENTS/SET_ALERT`,
  ERROR: `${key}/SEGMENTS/ERROR`
}

const SNACKBAR = {
  CLOSE: `${key}/SNACKBAR/CLOSE`,
  SET: `${key}/SNACKBAR/SET`
}

export default {
  FOLLOWUPS,
  TOUCHPOINT,
  SCRIPTS,
  SEGMENTS,
  SNACKBAR
}
