export const key = 'newPhoneInquiry'

const SUBMIT = {
  SEND: `${key}/SUBMIT/SEND`,
  ERROR: `${key}/SUBMIT/ERROR`,

  RECEIVE_SUCCESS: `${key}/SUBMIT/RECEIVE_SUCCESS`,
  RECEIVE_ERROR: `${key}/SUBMIT/RECEIVE_ERROR`,

  RECEIVE_APPT_SUCCESS: `${key}/SUBMIT/RECEIVE_APPT_SUCCESS`,
  RECEIVE_APPT_ERROR: `${key}/SUBMIT/RECEIVE_APPT_ERROR`
}

const DATA = {
  SET: `${key}/DATA/SET`,
  TOGGLE_APPOINTMENT: `${key}/DATA/TOGGLE_APPOINTMENT`,

  CLEAR: `${key}/DATA/CLEAR`,

  REQUEST_USER_DATA: `${key}/DATA/REQUEST_USER_DATA`,
  RECEIVE_USER_DATA: `${key}/DATA/RECEIVE_USER_DATA`,

  REQUEST_EMPLOYEES_DATA: `${key}/DATA/REQUEST_EMPLOYEES_DATA`,
  RECEIVE_EMPLOYEES_DATA: `${key}/DATA/RECEIVE_EMPLOYEES_DATA`,

  REQUEST_SCRIPT_DATA: `${key}/DATA/REQUEST_SCRIPT_DATA`,
  RECEIVE_SCRIPT_DATA: `${key}/DATA/RECEIVE_SCRIPT_DATA`,

  SELECT_LOCATION: `${key}/DATA/SELECT_LOCATION`
}

export default {
  SUBMIT,
  DATA
}
